spring:
  application:
    name: aggregator

  datasource:
    url: jdbc:postgresql://localhost:5432/aggregator_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  ai:
    model:
      chat: ollama
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: mistral

csv-source:
  configs:

    PAYPAL:
      header-line: '"Date","Time","TimeZone","Name","Type","Status","Currency","Amount","Fees","Total","Exchange Rate","Receipt ID","Balance","Transaction ID","Item Title"'
      date-key: Date
      amount-key: Amount
      description-key: Item Title
      date-format: 'yyyy/MM/dd'

    FNB:
      header-line: 'Date, Amount, Balance, Description'
      date-key: Date
      amount-key: Amount
      description-key: Description
      date-format: 'yyyy/MM/dd'

    ABSA:
      header-line: 'Date,Transaction Type,Description,Amount,Balance,Currency'
      date-key: Date
      amount-key: Amount
      description-key: Description
      date-format: 'yyyy-MM-dd'