spring:
  application:
    name: aggregator

  datasource:
    url: jdbc:postgresql://localhost:5432/aggregator_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  ai:
    model:
      chat: ollama
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: mistral

# This was designed as a ConfigurationProperties just because this would make it easier to see
# how support for additional sources can be added. For a proper API, make this a DB entity
# so that support for more sources can be added during runtime.

csv-source:
  configs:

    CAPITEC:
      header-line: 'Nr,Account,Posting Date,Transaction Date,Description,Original Description,Parent Category,Category,Money In,Money Out,Fee,Balance'
      date-key: Posting Date
      amount-key: Money In,Money Out,Fee
      description-key: Description,Category
      date-format: 'yyyy-MM-dd'

    PAYPAL:
      header-line: '"Date","Time","TimeZone","Name","Type","Status","Currency","Amount","Fees","Total","Exchange Rate","Receipt ID","Balance","Transaction ID","Item Title"'
      date-key: Date
      amount-key: Amount
      description-key: Item Title
      date-format: 'yyyy/MM/dd'

    FNB:
      header-line: 'Date, Amount, Balance, Description'
      date-key: Date
      amount-key: Amount
      description-key: Description
      date-format: 'yyyy/MM/dd'

    ABSA:
      header-line: 'Date,Transaction Type,Description,Amount,Balance,Currency'
      date-key: Date
      amount-key: Amount
      description-key: Description
      date-format: 'yyyy-MM-dd'

    #In the event of multiple relevant keys for "amount" and "description", add them all separated with commas
    #(See Capitec as an example)
    NEW SOURCE:
      header-line: 'Paste header line here (keep single quotes)'
      date-key: What your CSV header calls the "Date" column
      amount-key: What your CSV header calls the "Amount" column
      description-key: What your CSV header calls the "Description" column
      date-format: 'eg. yyyy-MM-dd, yyyy/MM/dd, etc.'