services:
  db:
    image: postgres:17
    container_name: postgres-container
    restart: always
    environment:
      POSTGRES_DB: aggregator_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: aggregator-api
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-container:5432/aggregator_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password

#  ui:
#    build:
#      context: ../aggregator-ui
#      dockerfile: Dockerfile
#    ports:
#      - "80:80"
#    depends_on:
#      - api

volumes:
  postgres_data: